# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: benjamin.vial84@gmail.com
author_name: Benjamin Vial
data_format: string
file_extension: ''
has_binder: false
has_settings: false
kind: theme
labextension_name: jlabcss
mimetype: ''
mimetype_name: ''
project_short_description: A JupyterLab theme
python_name: jlabcss
repository: ''
test: true
viewer_name: ''

